name: CI

on: [push]

jobs:
    FrontDeploy:
        name: FrontDeploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Setup Node and Install Dependencies
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  registry-url: "https://registry.npmjs.org"

            - name: Install Firebase Tools
              run: npm install -g firebase-tools

            - name: Deploy to Firebase Hosting
              run: |
                  firebase deploy --token $FIREBASE_TOKEN --project learn-2dfb8 
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
